#!/usr/bin/env node
// PreToolUse(Bash) hook: block `git commit` invocations that would add
// AI/coding-agent attribution to the commit message (Co-Authored-By Claude,
// "Generated with Claude Code", etc.).
//
// The workspace policy (every CLAUDE.md in file-parser/) forbids AI
// attribution in commits. This hook turns the rule into a hard gate so
// Claude cannot accidentally violate it.
//
// Exit codes:
//   0 — allow
//   2 — block; stderr is fed back to the model

import { existsSync, readFileSync } from 'node:fs'

const FORBIDDEN_PATTERNS = [
    /co-authored-by:.*claude/i,
    /co-authored-by:.*anthropic/i,
    /co-authored-by:.*codex/i,
    /generated.{0,20}with.{0,20}claude/i,
    /\bclaude\s*code\b/i,
    /🤖.*generated/i,
]

async function readEvent() {
    return new Promise((resolve) => {
        let buf = ''
        process.stdin.setEncoding('utf8')
        process.stdin.on('data', (c) => (buf += c))
        process.stdin.on('end', () => {
            try { resolve(JSON.parse(buf)) } catch { resolve(null) }
        })
        setTimeout(() => resolve(null), 200)
    })
}

const evt = await readEvent()
if (!evt) process.exit(0)
if (evt.tool_name !== 'Bash') process.exit(0)

const cmd = String(evt?.tool_input?.command || '')
// Only police git commit / git commit --amend.
if (!/\bgit\s+commit\b/.test(cmd)) process.exit(0)

// Pull the commit message out of -m / -F /  --message= / HEREDOC.
let message = ''

// -m "msg" or -m 'msg' or --message="msg"
const dashM = cmd.match(/-m\s+(['"])([\s\S]*?)\1/) || cmd.match(/--message=(['"])([\s\S]*?)\1/)
if (dashM) message += dashM[2] + '\n'

// HEREDOC: cat <<'EOF' ... EOF
const heredoc = cmd.match(/cat\s+<<['"]?(\w+)['"]?[\s\S]*?\n([\s\S]*?)\n\s*\1\s*\)/)
if (heredoc) message += heredoc[2] + '\n'

// -F file.txt: read it
const dashF = cmd.match(/-F\s+(\S+)/)
if (dashF && existsSync(dashF[1])) {
    try { message += readFileSync(dashF[1], 'utf8') + '\n' } catch { /* ignore */ }
}

if (!message.trim()) process.exit(0)

const violations = []
for (const re of FORBIDDEN_PATTERNS) {
    const m = message.match(re)
    if (m) violations.push(m[0])
}

if (violations.length === 0) process.exit(0)

console.error([
    '[commit-attribution-guard] BLOCKED: commit message contains AI/coding-agent attribution.',
    '',
    'Workspace policy (~/work/file-parser/CLAUDE.md): never add Co-Authored-By, Generated by,',
    'tool-signature footers, or any other AI/coding-agent attribution to commits.',
    '',
    'Matched fragments:',
    ...violations.map((v) => `  - ${v}`),
    '',
    'Fix: rewrite the commit message without the attribution, then retry.',
].join('\n'))
process.exit(2)
